version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /index2.html
    destination: /var/www/html/
  - source: /refund1.html
    destination: /var/www/html/
  - source: /backgroundfile.jpg
    destination: /var/www/html/
  - source: /goldcoin.jpg
    destination: /var/www/html/
  - source: /index2background.jpg
    destination: /var/www/html/
  - source: /process.php
    destination: /var/www/html/
  - source: /processrefund.php
    destination: /var/www/html/
  - source: /processserver.php
    destination: /var/www/html/
  - source: /refundbackground.jpg
    destination: /var/www/html/
  - source: /refundbutton.jpeg
    destination: /var/www/html/	
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
